// <auto-generated />
using System;
using BankingApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918195500_AccountSeedData")]
    partial class AccountSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingApp.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("360b7962-1b37-4880-a87e-c244d1001e52"),
                            AccountNumber = "693762756416",
                            Currency = "USD",
                            CustomerId = new Guid("7222f4a6-b8ca-4cc5-ad74-7b4b34d79779"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("06320057-2872-42af-a09a-6635ee881ddb"),
                            AccountNumber = "990888064302",
                            Currency = "USD",
                            CustomerId = new Guid("7222f4a6-b8ca-4cc5-ad74-7b4b34d79779"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("d48b9479-c96f-4402-a356-4d2f830aab71"),
                            AccountNumber = "660279434684",
                            Currency = "USD",
                            CustomerId = new Guid("4bf2a680-ac31-4206-be1a-8effc3d6c427"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b131623b-44ec-4e60-84e2-23ee5638e28d"),
                            AccountNumber = "752142281253",
                            Currency = "USD",
                            CustomerId = new Guid("4bf2a680-ac31-4206-be1a-8effc3d6c427"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("29feb7be-21e0-4f55-90ca-df47379569ba"),
                            AccountNumber = "416459422322",
                            Currency = "USD",
                            CustomerId = new Guid("afbd278c-5176-4510-9ad1-ae2acf34f80a"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("8a0e9a6a-0ea3-4439-9fdc-20860f836f42"),
                            AccountNumber = "145967913707",
                            Currency = "USD",
                            CustomerId = new Guid("afbd278c-5176-4510-9ad1-ae2acf34f80a"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5ccf1509-a6f3-42d2-9cc7-3b3fab726300"),
                            AccountNumber = "228947707340",
                            Currency = "USD",
                            CustomerId = new Guid("418586f3-7268-4035-8ae7-d2241c474876"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e65ae612-bc01-431a-ad1f-7d6c19a74e34"),
                            AccountNumber = "681627673954",
                            Currency = "USD",
                            CustomerId = new Guid("418586f3-7268-4035-8ae7-d2241c474876"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("418586f3-7268-4035-8ae7-d2241c474876"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1997, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Email = "omarwilliams@gmail.com",
                            FirstName = "Omar",
                            LastName = "Williams",
                            PhoneNumber = "111-111-1111"
                        },
                        new
                        {
                            Id = new Guid("4bf2a680-ac31-4206-be1a-8effc3d6c427"),
                            DateOfBirth = new DateTimeOffset(new DateTime(2010, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            Email = "harlemwilliams@gmail.com",
                            FirstName = "Harlem",
                            LastName = "Williams",
                            PhoneNumber = "222-222-2222"
                        },
                        new
                        {
                            Id = new Guid("7222f4a6-b8ca-4cc5-ad74-7b4b34d79779"),
                            DateOfBirth = new DateTimeOffset(new DateTime(1995, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Email = "tylerrowlette@gmail.com",
                            FirstName = "Tyler",
                            LastName = "Rowlette",
                            PhoneNumber = "333-333-3333"
                        },
                        new
                        {
                            Id = new Guid("afbd278c-5176-4510-9ad1-ae2acf34f80a"),
                            DateOfBirth = new DateTimeOffset(new DateTime(2005, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            Email = "jerseyrowlette@gmail.com",
                            FirstName = "Jerey",
                            LastName = "Rowlette",
                            PhoneNumber = "444-444-4444"
                        });
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Account", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.LedgerEntry", b =>
                {
                    b.HasOne("BankingApp.Domain.Entities.Account", null)
                        .WithMany("LedgerEntries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingApp.Domain.Entities.Transaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId");

                    b.OwnsOne("BankingApp.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("LedgerEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("LedgerEntryId");

                            b1.ToTable("LedgerEntries");

                            b1.WithOwner()
                                .HasForeignKey("LedgerEntryId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Account", b =>
                {
                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("BankingApp.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
